### ISSUE TITLE
Memory leak in decoding process

### ISSUE THREAD

**Issue by kevmo314** [facebookresearch/encodec#19]
## 🐛 Bug Report

I'm trying to evaluate Encodec for streaming audio use cases, however I noticed that the decoding step seems to accumulate memory very quickly over time. If I turn off decoding, memory usage stays constant. I looked at the code though, I'm not sure why?

## To Reproduce

```
from encodec import EncodecModel
from encodec.utils import convert_audio

import torchaudio
import torch

# Instantiate a pretrained EnCodec model
model = EncodecModel.encodec_model_24khz()
model.set_target_bandwidth(6.0)

# Load and pre-process the audio waveform
wav, sr = torchaudio.load("CantinaBand60.wav")
wav = wav.unsqueeze(0)
wav = convert_audio(wav, sr, model.sample_rate, model.channels)

# Extract discrete codes from EnCodec
frames = []
for offset in range(0, 1440000, 480):
    print(offset)

    encoded_frames = model._encode_frame(wav[:, :, offset: offset + 480])

    frames.append(model._decode_frame(encoded_frames))

# merge the decoded frames
decoded = torch.cat(frames, dim=2)

# save the decoded audio
torchaudio.save("decoded.wav", decoded, model.sample_rate)
```

## Expected behavior

Memory shouldn't be persisted across frames.

## Actual Behavior

Memory usage grows over time eventually resulting in OOM.

**Comment by adefossez** [comment]
you need to wrap the eval of the model with `torch.no_grad()`, I've updated the readme to include it !

**Comment by adefossez** [comment]
I'll be closing the issue, please reopen if that didn't solve your issue.
