### ISSUE TITLE
Will there be some audio samples of `Model architecture Analysis` part ?

### ISSUE THREAD

**Issue by BakerBunker** [facebookresearch/encodec#27]
## ❓ Questions

Thank you for the excellent experiment detail in the paper. Some model architecture analysis were done in Table A.3, I'm curious about what the actual audio sounds like, it should be more intuitive than the metrics in the table.

**Comment by adefossez** [comment]
Hello @BakerBunker , we haven't planned on releasing audio for intermediate models.
