### ISSUE TITLE
Questions about dataset mixture strategy

### ISSUE THREAD

**Issue by zerlinwang** [facebookresearch/encodec#36]
## ❓ Questions

Thanks for your amazing work!
I have a question about your dataset mixing strategy. Does `mixture` here refer to:
1. a combination of audios from different datasets so no change per training audio, or
2. a superposition of different audio tracks, so each training audio contains multiple tracks from multiple datasets?

![image](https://user-images.githubusercontent.com/80957609/221408139-e35b6539-24dc-4b87-bae1-cbafee8a8f0e.png)

**Comment by adefossez** [comment]
this is the sum of two audio from two different datasets (sometimes even 3 audio).

**Comment by zerlinwang** [comment]
Thanks for your answer!
