### ISSUE TITLE
Inference using a GPU

### ISSUE THREAD

**Issue by lucasbr15** [facebookresearch/encodec#4]
## ❓ Questions

Hello, my question is the following, i would like to know if it's possible in any way to use cuda acceleration to process compressing and decompressing using Encodec? from what i've been reading i couldn't find anything that mentioned inference by gpu.. so i wanted to know if it's possible to use the gpu, that would be even more productive and useful, awaiting an answer, thank you in advance, att. Lucas.

**Comment by mimbres** [comment]
@lucasbr15 Yes, it's possible with a few lines of modifications. Take a look at my forked [repo](https://github.com/mimbres/encodec) or https://github.com/mimbres/encodec/blob/main/encodec/__main__.py

- '-g' or '--gpu' option is added for the use of GPU. 
- '-t' or '--time' option for displaying elapse time.

**Comment by lucasbr15** [comment]
> 

@mimbres I'm really grateful for your repository now that it's using the gpu it's much faster, before a 3 minute audio took 1m 30s, now it only takes 20 seconds! once again, thank you!
