### ISSUE TITLE
Non-free LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [facebookresearch/encodec#49]
Non-commercial (NC) clauses are non-free as they are not free software according to the [FSF](https://www.gnu.org/philosophy/free-sw.html#selling), open source according to the [OSI](https://opensource.org/osd#free-redistribution), or free culture according to [Freedom Defined](https://freedomdefined.org/Definition).  I would recommend using CC-BY-SA-4.0, CC-BY-4.0, or CC-0-1.0 instead which are free culture Creative Commons licenses.

**Comment by adefossez** [comment]
The code is now available under the MIT license :)

**Comment by lesniewski** [comment]
Could you confirm that the pretrained model weights are also covered under the MIT license? Thank you!

**Comment by TechnologyClassroom** [comment]
Software licenses depend on copyright. Can a model checkpoint even be under copyright? [This YouTube video argues that they cannot fall under copyright.](https://www.youtube.com/watch?v=W5M-dvzpzSQ?t=16m50s)
