### ISSUE TITLE
Question about better quality models for 48 kHz

### ISSUE THREAD

**Issue by StephanAXX** [facebookresearch/encodec#55]
Do you have better quality models for 48 kHz?

I've been helpful if you add 32 kbps, 48 kbps, 64 kbps and 96 kbps models to compare to MP3 / AAC / Windows Media Audio.

Thanks for the support!

**Comment by listener17** [comment]
@StephanAXX: I'm not from Meta :-) Question to you: do you know if the 48 kHz model can do mono coding? Or is it only stereo?

**Comment by StephanAXX** [comment]
(In reply from [listener17](https://github.com/listener17)):

> @StephanAXX: I'm not from Meta :-) Question to you: do you know if the 48 kHz model can do mono coding? Or is it only stereo?

Only stereo, the 48 kHz model can't do mono! The 24 kHz model can do only mono, no stereo! Mono encoding to the 48 kHz model will be added soon!
