### ISSUE TITLE
Transparency 

### ISSUE THREAD

**Issue by 89z** [facebookresearch/encodec#6]
Is a recommendation available for getting transparency with this package? Is it 24 kbps? higher?

https://wikipedia.org/wiki/Transparency_(data_compression)

**Comment by 89z** [comment]
looks like some are saying that 24 kbps is not currently high enough:

https://news.ycombinator.com/item?id=33404249

so it seems transparency might not currently be possible

**Comment by Firepal** [comment]
A model trained to generate higher-bitrate files is not provided...

**Comment by Limeysoda1** [comment]
I agree, no long I could encode sounded transparent, a slightly higher bitrate is needed for music transparency

**Comment by adefossez** [comment]
We do not aim for audio transparency with this codec. At the moment it is not so easy to get rid of the remaining artifacts even when allowing the model to use a larger bandwidth. Thus for the moment deep learning really shines for super low bitrates application but future research is required for transparent and fast deep learning based codecs at higher bandwidth.
