### ISSUE TITLE
About audio quality evaluation

### ISSUE THREAD

**Issue by sh-lee-prml** [facebookresearch/encodec#9]
## ❓ Questions

Thank you for nice work.

I have some question about objective evaluation metrics.

1. Are these metrics (SI-SNR and ViSQOL) consistent with audio quality perceptually?

I know that it is very difficult to evaluate the audio quality. So I'm so curious how to evaluate the model during ablation studies or during training.

2. MS-STFT discriminator (Complex) VS MS-STFT discriminator (Real)

How about the quality of the model with MS-STFT discriminator using only real value? It would be appreciated if you could share such information.

Thank you!

**Comment by adiyoss** [comment]
Hi @sh-lee-prml,
1) These metrics consistent with human perception up to some level, they are definitely not perfect, but can give you a nice proxy for faster model evaluation. Anyways, we recommend running full subjective tests in addition to these metrics once you reach a good enough model.
2) During preliminary experiments we found that the complex MS-STFT was better for us, so we kept developing it. So as we did not do an in-depth comparison, I can not say much about the exact differences in quality between them.

**Comment by sh-lee-prml** [comment]
Thank you!

**Comment by stonelazy** [comment]
> 1. Are these metrics (SI-SNR and ViSQOL) consistent with audio quality perceptually?
> 
> I know that it is very difficult to evaluate the audio quality. So I'm so curious how to evaluate the model during ablation studies or during training.

For SpeechEnhancement [DNSMOS](https://github.com/microsoft/DNS-Challenge/tree/master/DNSMOS) did really give a better objective evaluation when subjective evaluation isn't feasible. Not sure if the same applies for this problem (even though it's a non-intrusive evaluation metric). I would suggest giving DNSMOS a try.

**Comment by adefossez** [comment]
DNSMos definitely look interesting! Visqol is supposed to correlate to human perception but definitely has a lot of shortcomings and fail to capture the presence of artifact. While we are unlikely to go back to the evaluation stage of Encodec, having already conducted extensive evaluation, we will keep that in mind for future work!

**Comment by listener17** [comment]
@sh-lee-prml: is it possible for you to share your training script?
